### PR TITLE
Updated TROUBLESHOOTING.md with the anchors

### PR DESCRIPTION
**Pull request by opopovss**
## Pull request description

"Added anchors to troubleshooting tabs, to easier access to right one tip"

## Checklist
- [x] I have successful end to end tests run (with & without domain)
- [x] I have added unit tests (if applicable)
- [x] I have user documentation (if applicable)

### CODE REVIEW

**Comment by bianchi2** [comment]
Hi @opopovss thanks for your contribution. I have run your branch locally and this change seem to break the troubleshooting page. This is what I see:

image

Tips cannot be expanded (the error button does nothing). Also, markdown syntax is gone.

You can run docs locally, just run `make docs` in the root of the repository.

**Comment by opopovss** [comment]
> 
Thanks, @bianchi2 , I will take a look and fix the issue

**Comment by opopovss** [comment]
@bianchi2 Could you please review the changes

**Comment by bianchi2** [comment]
thanks @opopovss Yes, definitely looks better now. Quick question though, the anchors themselves are below the title:

image

Is this expected? In any case, it looks nicer and it's more convenient to share links to troubleshooting docs.

**Comment by opopovss** [comment]
> thanks @opopovss Yes, definitely looks better now. Quick question though, the anchors themselves are below the title:
> 
> image
> 
> Is this expected? In any case, it looks nicer and it's more convenient to share links to troubleshooting docs.

Yes, this is to be expected and this is the smallest visualization of the permalink I could make.

**Pull request merged**
